[package]
name = "photorofls"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", features = ["bmp", "jpeg", "png", "ico", "tga", "tiff", "webp", "exr"], default-features = false }
clap = { version = "4.5.23", features = ["derive"] }